services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - postgresql
      - php
      - node
  php:
    build:
      context: docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./src:/var/www/laravel
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - env/postgres.env
    volumes:
      - db_data:/var/lib/postgresql/data
  node:
    image: node:18
    working_dir: /var/www/laravel
    volumes:
      - ./src:/var/www/laravel
    command: "sh -c 'npm install && npm run build'"


  composer:
    build:
      context: docker/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
  artisan:
    build:
      context: docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  db_data:
